export default {
	login: "ei-bro",
	id: 78224716,
	node_id: "MDQ6VXNlcjc4MjI0NzE2",
	avatar_url: "https://avatars.githubusercontent.com/u/78224716?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/ei-bro",
	html_url: "https://github.com/ei-bro",
	followers_url: "https://api.github.com/users/ei-bro/followers",
	following_url: "https://api.github.com/users/ei-bro/following{/other_user}",
	gists_url: "https://api.github.com/users/ei-bro/gists{/gist_id}",
	starred_url: "https://api.github.com/users/ei-bro/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/ei-bro/subscriptions",
	organizations_url: "https://api.github.com/users/ei-bro/orgs",
	repos_url: "https://api.github.com/users/ei-bro/repos",
	events_url: "https://api.github.com/users/ei-bro/events{/privacy}",
	received_events_url: "https://api.github.com/users/ei-bro/received_events",
	type: "User",
	site_admin: false,
	name: "Ibrahim",
	company: "Evangadi Tech",
	blog: "ibrahimwondimu.com",
	location: "Addis Ababa, Ethiopia",
	email: null,
	hireable: null,
	bio: '"The Secret To Creativity Is Knowing how To find Your Sources."\r\n\r\n',
	twitter_username: null,
	public_repos: 9,
	public_gists: 0,
	followers: 5,
	following: 2,
	created_at: "2021-01-29T16:35:18Z",
	updated_at: "2023-02-01T10:19:39Z",
};
